

name: forja_trabajo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true